added rate limit

diff --git a/deploy2inveniordm b/deploy2inveniordm
--- a/deploy2inveniordm
+++ b/deploy2inveniordm
@@ -3,7 +3,7 @@ set -e -v
 
 #    deploy2inveniordm
 #    Copyright (C) 2026  Daniel Mohr
-#    Version: 0.7.3
+#    Version: 0.8.0
 #    DOI: 10.5281/zenodo.10112959
 #
 # Instead of command line parameters we use environment variables.
@@ -24,6 +24,7 @@ set -e -v
 #   * DEPLOY2INVENIORDM_CURL_MAX_TIME
 #   * DEPLOY2INVENIORDM_CURL_MAX_TIME_PUBLISH
 #   * DEPLOY2INVENIORDM_ADD_IsCompiledBy_DEPLOY2INVENIORDM
+#   * DEPLOY2INVENIORDM_RATE_LIMIT
 #
 # DEPLOY2INVENIORDM_SKIP_NEW_VERSION is no longer needed.
 # deploy2inveniordm automatically creates new version or reuses existing draft.
@@ -48,16 +49,23 @@ set -e -v
 set +v
 
 log() {
-    echo "$(date +"%H:%M:%S")" "$*"
+    echo "$(date -Iseconds)" "$*"
+}
+warnlog() {
+    printf "\033[0;33m%s %s\033[0m\n" "$(date -Iseconds)" "$*" 1>&2;
 }
 errlog() {
     printf "\033[0;31m%s %s\033[0m\n" "$(date -Iseconds)" "$*" 1>&2;
+}
+echojq() {
+    echo "$1:"
+    echo "$2" | jq -C . || (errlog "$2"; exit 3)
 }
 
 VERSION=$(sed -n 's/^#.*Version:\s*\(\S*\)$/\1/p' "$0")
 DEPLOY2ZENODO_DOI=$(sed -n 's/^#.*DOI:\s*\(\S*\)$/\1/p' "$0")
 
-echo "$(date -Iseconds) run deploy2inveniordm v$VERSION (DOI: $DEPLOY2ZENODO_DOI)"
+log "run deploy2inveniordm v$VERSION (DOI: $DEPLOY2ZENODO_DOI)"
 
 # check available variables
 log "check available variables"
@@ -72,9 +80,30 @@ if [ -n "$missing_variables" ]; then
     errlog "missing variables are at least:$missing_variables"
     exit 1
 else
+    if [ -z "$DEPLOY2INVENIORDM_RATE_LIMIT" ] || [ "$DEPLOY2INVENIORDM_RATE_LIMIT" = "auto" ]; then
+	# estimate useful sleep time as rate limit
+	n=$(echo "$DEPLOY2INVENIORDM_UPLOAD" | wc -w)
+	total_calls=$((4 * n + 6))
+        if [ $total_calls -lt 23 ]; then
+            DEPLOY2INVENIORDM_RATE_LIMIT=0
+        else
+            DEPLOY2INVENIORDM_RATE_LIMIT=2.142857
+        fi
+	warnlog "WARNING: automatically set DEPLOY2INVENIORDM_RATE_LIMIT=$DEPLOY2INVENIORDM_RATE_LIMIT"
+        warnlog "because $total_calls API calls are expected"
+    else
+        if ! (echo "$DEPLOY2INVENIORDM_RATE_LIMIT" | grep -q -E "^[0-9]+\.?[0-9]*$"); then
+	    warnlog "WARNING: do not understand DEPLOY2INVENIORDM_RATE_LIMIT"
+	    DEPLOY2INVENIORDM_RATE_LIMIT=2.142857
+	    warnlog "using default value: DEPLOY2INVENIORDM_RATE_LIMIT=$DEPLOY2INVENIORDM_RATE_LIMIT"
+        fi
+    fi
+    if [ -n "$DEPLOY2INVENIORDM_DRYRUN" ] || [ -n "$DEPLOY2INVENIORDM_SKIPRUN" ]; then
+	warnlog "WARNING: DRYRUN or SKIPRUN is enabled. API calls will be mocked/skipped."
+    fi
     log "available variables are looking fine"
-    for varname in DEPLOY2INVENIORDM_API_URL DEPLOY2INVENIORDM_DEPOSITION_ID DEPLOY2INVENIORDM_JSON DEPLOY2INVENIORDM_UPLOAD DEPLOY2INVENIORDM_SKIP_PUBLISH DEPLOY2INVENIORDM_DRYRUN DEPLOY2INVENIORDM_SKIPRUN DEPLOY2INVENIORDM_GET_METADATA DEPLOY2INVENIORDM_SKIP_UPLOAD DEPLOY2INVENIORDM_CURL_MAX_TIME DEPLOY2INVENIORDM_CURL_MAX_TIME_PUBLISH DEPLOY2INVENIORDM_ADD_IsCompiledBy_DEPLOY2INVENIORDM; do
-        echo "$varname: \"$(eval "echo \"\$$varname\"")\""
+    for varname in DEPLOY2INVENIORDM_API_URL DEPLOY2INVENIORDM_DEPOSITION_ID DEPLOY2INVENIORDM_JSON DEPLOY2INVENIORDM_UPLOAD DEPLOY2INVENIORDM_SKIP_PUBLISH DEPLOY2INVENIORDM_DRYRUN DEPLOY2INVENIORDM_SKIPRUN DEPLOY2INVENIORDM_GET_METADATA DEPLOY2INVENIORDM_SKIP_UPLOAD DEPLOY2INVENIORDM_CURL_MAX_TIME DEPLOY2INVENIORDM_CURL_MAX_TIME_PUBLISH DEPLOY2INVENIORDM_ADD_IsCompiledBy_DEPLOY2INVENIORDM DEPLOY2INVENIORDM_RATE_LIMIT; do
+        log "$varname: \"$(eval "echo \"\$$varname\"")\""
     done
 fi
 
@@ -98,12 +127,7 @@ fi
 
 CURL_MAX_TIME_PUBLISH=${DEPLOY2INVENIORDM_CURL_MAX_TIME_PUBLISH:-300}
 hjson='Content-Type: application/json'
-alias curlauth='curl --header "Authorization: Bearer $DEPLOY2INVENIORDM_ACCESS_TOKEN" --max-time "${DEPLOY2INVENIORDM_CURL_MAX_TIME:-60}"'
-
-echojq() {
-    echo "$1:"
-    echo "$2" | jq -C . || (errlog "$2"; exit 3)
-}
+alias curlauth='sleep "$DEPLOY2INVENIORDM_RATE_LIMIT"; curl --header "Authorization: Bearer $DEPLOY2INVENIORDM_ACCESS_TOKEN" --max-time "${DEPLOY2INVENIORDM_CURL_MAX_TIME:-60}"'
 
 echo "content of DEPLOY2INVENIORDM_JSON:"
 jq -C . "$DEPLOY2INVENIORDM_JSON"
@@ -114,11 +138,15 @@ if [ -z "$DEPLOY2INVENIORDM_SKIPRUN" ]; then
     log "check publication_date=\"$PUBLICATION_DATE\" in DEPLOY2INVENIORDM_JSON is EDTF Level 0"
     if [ -n "$PUBLICATION_DATE" ] && [ "$PUBLICATION_DATE" != "null" ]; then
         RE_EDTF_LEVEL_0="((^[0-9]{4}-[0-9]{2}-[0-9]{2}$)|(^[0-9]{4}-[0-9]{2}$)|(^[0-9]{4}$))|(((^[0-9]{4}-[0-9]{2}-[0-9]{2})|(^[0-9]{4}-[0-9]{2})|(^[0-9]{4}))/(([0-9]{4}-[0-9]{2}-[0-9]{2}$)|([0-9]{4}-[0-9]{2}$)|([0-9]{4}$)))"
-        echo "$PUBLICATION_DATE" | grep -q -E "$RE_EDTF_LEVEL_0"
+	if ! (echo "$PUBLICATION_DATE" | grep -q -E "$RE_EDTF_LEVEL_0"); then
+            errlog "ERROR: publication_date '$PUBLICATION_DATE' is not valid EDTF Level 0."
+            exit 35
+	fi
         log "publication_date is EDTF Level 0"
     else
-        log "publication_date is empty or not given: set to now ($(date +"%Y-%m-%d"))"
-        DEPLOY2INVENIORDM_JSON_DATA=$(echo "$DEPLOY2INVENIORDM_JSON_DATA" | jq -c ".metadata.publication_date = \"$(date +"%Y-%m-%d")\"")
+	publication_date="$(date +"%Y-%m-%d")"
+        warnlog "publication_date is empty or not given: set to now ($publication_date)"
+        DEPLOY2INVENIORDM_JSON_DATA=$(echo "$DEPLOY2INVENIORDM_JSON_DATA" | jq -c ".metadata.publication_date = \"$publication_date\"")
     fi
 fi
 
@@ -199,7 +227,7 @@ if [ "$DEPLOY2INVENIORDM_DEPOSITION_ID" = "create NEW record" ]; then
                 log "Skip testing checksum due to DRYRUN or SKIPRUN."
             else
                 test -n "$CHECKSUMRAW" -a "$CHECKSUMRAW" != "null" || (errlog "CHECKSUMRAW=\"$CHECKSUMRAW\""; exit 7)
-                echo "$CHECKSUM  $filename" | md5sum -c -
+		echo "$CHECKSUM  $filename" | md5sum -c - || (errlog "checksum verification failed: $CHECKSUM $filename"; exit 36)
             fi
         done
         log "files uploaded"
@@ -280,7 +308,7 @@ else
     NEWDOIJSON="$(curlauth --header 'Accept: application/vnd.inveniordm.v1+json' --header "$hjson" --request POST "$RESERVEDOI")"
     echojq NEWDOIJSON "$NEWDOIJSON"
     NEWDOI=$(echo "$NEWDOIJSON" | jq -r .pids.doi.identifier)
-    echo "NEWDOI: $NEWDOI"
+    log "NEWDOI: $NEWDOI"
     if [ -n "$DEPLOY2INVENIORDM_DRYRUN" ] || [ -n "$DEPLOY2INVENIORDM_SKIPRUN" ]; then
         log "Skip testing new doi due to DRYRUN or SKIPRUN."
     else
@@ -301,7 +329,7 @@ else
     #for id in $(echo "$UPLOADMETADATA" | jq -r ".files[] | .id"); do
     for id in $(echo "$UPLOADMETADATA" | jq -r ".files.entries | keys | .[]"); do
         log "remove file with id \"$id\""
-        echo "$LATESTDRAFT"/files/"$id"
+        log "$LATESTDRAFT"/files/"$id"
         DELETEFILE=$(curlauth --header 'Accept: application/vnd.inveniordm.v1+json' --request DELETE "$LATESTDRAFT"/files/"$id")
         echojq DELETEFILE "$DELETEFILE"
     done
@@ -342,7 +370,7 @@ else
                 log "Skip testing checksum due to DRYRUN or SKIPRUN."
             else
                 test -n "$CHECKSUMRAW" -a "$CHECKSUMRAW" != "null" || (errlog "CHECKSUMRAW=\"$CHECKSUMRAW\""; exit 18)
-                echo "$CHECKSUM  $pathname" | md5sum -c -
+		echo "$CHECKSUM  $pathname" | md5sum -c - || (errlog "checksum verification failed: $CHECKSUM $pathname"; exit 37)
             fi
         done
         log "files uploaded"
@@ -392,6 +420,6 @@ if [ -n "$DEPLOY2INVENIORDM_GET_METADATA" ]; then
     fi
 fi
 
-echo "$(date -Iseconds) finished deploy2inveniordm v$VERSION"
+log "$(date -Iseconds) finished deploy2inveniordm v$VERSION"
 
 # stop deploy2inveniordm
diff --git a/deploy2zenodo b/deploy2zenodo
--- a/deploy2zenodo
+++ b/deploy2zenodo
@@ -3,7 +3,7 @@ set -e -v
 
 #    deploy2zenodo
 #    Copyright (C) 2023-2026  Daniel Mohr
-#    Version: 0.7.3
+#    Version: 0.8.0
 #    DOI: 10.5281/zenodo.10112959
 #
 # Instead of command line parameters we use environment variables.
@@ -27,6 +27,7 @@ set -e -v
 #   * DEPLOY2ZENODO_ADD_IsCompiledBy_DEPLOY2ZENODO
 #   * DEPLOY2ZENODO_ADD_IsNewVersionOf
 #   * DEPLOY2ZENODO_ADD_IsPartOf
+#   * DEPLOY2ZENODO_RATE_LIMIT
 #
 # For more information see: https://gitlab.com/deploy2zenodo/deploy2zenodo
 #
@@ -48,16 +49,23 @@ set -e -v
 set +v
 
 log() {
-    echo "$(date +"%H:%M:%S")" "$*"
+    echo "$(date -Iseconds)" "$*"
+}
+warnlog() {
+    printf "\033[0;33m%s %s\033[0m\n" "$(date -Iseconds)" "$*" 1>&2;
 }
 errlog() {
     printf "\033[0;31m%s %s\033[0m\n" "$(date -Iseconds)" "$*" 1>&2;
+}
+echojq() {
+    echo "$1:"
+    echo "$2" | jq -C . || (errlog "$2"; exit 3)
 }
 
 VERSION=$(sed -n 's/^#.*Version:\s*\(\S*\)$/\1/p' "$0")
 DEPLOY2ZENODO_DOI=$(sed -n 's/^#.*DOI:\s*\(\S*\)$/\1/p' "$0")
 
-echo "$(date -Iseconds) run deploy2zenodo v$VERSION (DOI: $DEPLOY2ZENODO_DOI)"
+log "run deploy2zenodo v$VERSION (DOI: $DEPLOY2ZENODO_DOI)"
 
 # check available variables
 log "check available variables"
@@ -72,9 +80,30 @@ if [ -n "$missing_variables" ]; then
     errlog "missing variables are at least:$missing_variables"
     exit 1
 else
+    if [ -z "$DEPLOY2ZENODO_RATE_LIMIT" ] || [ "$DEPLOY2ZENODO_RATE_LIMIT" = "auto" ]; then
+	# estimate useful sleep time as rate limit
+	n=$(echo "$DEPLOY2ZENODO_UPLOAD" | wc -w)
+	total_calls=$((2 * n + 6))
+        if [ $total_calls -lt 23 ]; then
+            DEPLOY2ZENODO_RATE_LIMIT=0
+        else
+            DEPLOY2ZENODO_RATE_LIMIT=2.142857
+        fi
+	warnlog "WARNING: automatically set DEPLOY2ZENODO_RATE_LIMIT=$DEPLOY2ZENODO_RATE_LIMIT"
+        warnlog "because $total_calls API calls are expected"
+    else
+        if ! (echo "$DEPLOY2ZENODO_RATE_LIMIT" | grep -q -E "^[0-9]+\.?[0-9]*$"); then
+                warnlog "WARNING: do not understand DEPLOY2ZENODO_RATE_LIMIT"
+                DEPLOY2ZENODO_RATE_LIMIT=2.142857
+                warnlog "using default value: DEPLOY2ZENODO_RATE_LIMIT=$DEPLOY2ZENODO_RATE_LIMIT"
+        fi
+    fi
+    if [ -n "$DEPLOY2ZENODO_DRYRUN" ] || [ -n "$DEPLOY2ZENODO_SKIPRUN" ]; then
+	warnlog "WARNING: DRYRUN or SKIPRUN is enabled. API calls will be mocked/skipped."
+    fi
     log "available variables are looking fine"
-    for varname in DEPLOY2ZENODO_API_URL DEPLOY2ZENODO_DEPOSITION_ID DEPLOY2ZENODO_JSON DEPLOY2ZENODO_UPLOAD DEPLOY2ZENODO_SKIP_PUBLISH DEPLOY2ZENODO_DRYRUN DEPLOY2ZENODO_SKIPRUN DEPLOY2ZENODO_SKIP_NEW_VERSION DEPLOY2ZENODO_GET_METADATA DEPLOY2ZENODO_SKIP_UPLOAD DEPLOY2ZENODO_CURL_MAX_TIME DEPLOY2ZENODO_CURL_MAX_TIME_PUBLISH DEPLOY2ZENODO_ADD_IsCompiledBy_DEPLOY2ZENODO DEPLOY2ZENODO_ADD_IsNewVersionOf DEPLOY2ZENODO_ADD_IsPartOf; do
-        echo "$varname: \"$(eval "echo \"\$$varname\"")\""
+    for varname in DEPLOY2ZENODO_API_URL DEPLOY2ZENODO_DEPOSITION_ID DEPLOY2ZENODO_JSON DEPLOY2ZENODO_UPLOAD DEPLOY2ZENODO_SKIP_PUBLISH DEPLOY2ZENODO_DRYRUN DEPLOY2ZENODO_SKIPRUN DEPLOY2ZENODO_SKIP_NEW_VERSION DEPLOY2ZENODO_GET_METADATA DEPLOY2ZENODO_SKIP_UPLOAD DEPLOY2ZENODO_CURL_MAX_TIME DEPLOY2ZENODO_CURL_MAX_TIME_PUBLISH DEPLOY2ZENODO_ADD_IsCompiledBy_DEPLOY2ZENODO DEPLOY2ZENODO_ADD_IsNewVersionOf DEPLOY2ZENODO_ADD_IsPartOf DEPLOY2ZENODO_RATE_LIMIT; do
+        log "$varname: \"$(eval "echo \"\$$varname\"")\""
     done
 fi
 
@@ -96,14 +125,11 @@ if [ -n "$DEPLOY2ZENODO_SKIPRUN" ]; then
     }
 fi
 
+
+
 CURL_MAX_TIME_PUBLISH=${DEPLOY2ZENODO_CURL_MAX_TIME_PUBLISH:-300}
 hjson='Content-Type: application/json'
-alias curlauth='curl --header "Authorization: Bearer $DEPLOY2ZENODO_ACCESS_TOKEN" --max-time "${DEPLOY2ZENODO_CURL_MAX_TIME:-60}"'
-
-echojq() {
-    echo "$1:"
-    echo "$2" | jq -C . || (errlog "$2"; exit 3)
-}
+alias curlauth='sleep "$DEPLOY2ZENODO_RATE_LIMIT"; curl --header "Authorization: Bearer $DEPLOY2ZENODO_ACCESS_TOKEN" --max-time "${DEPLOY2ZENODO_CURL_MAX_TIME:-60}"'
 
 echo "content of DEPLOY2ZENODO_JSON:"
 jq -C . "$DEPLOY2ZENODO_JSON"
@@ -111,13 +137,16 @@ DEPLOY2ZENODO_JSON_DATA="$(jq -c . "$DEPLOY2ZENODO_JSON")"
 
 if [ -z "$DEPLOY2ZENODO_SKIPRUN" ]; then
     PUBLICATION_DATE=$(echo "$DEPLOY2ZENODO_JSON_DATA" | jq -r .metadata.publication_date)
-    echo "check publication_date=\"$PUBLICATION_DATE\" in DEPLOY2ZENODO_JSON is EDTF Level 0"
+    log "check publication_date=\"$PUBLICATION_DATE\" in DEPLOY2ZENODO_JSON is EDTF Level 0"
     if [ -n "$PUBLICATION_DATE" ] && [ "$PUBLICATION_DATE" != "null" ]; then
         RE_EDTF_LEVEL_0="((^[0-9]{4}-[0-9]{2}-[0-9]{2}$)|(^[0-9]{4}-[0-9]{2}$)|(^[0-9]{4}$))|(((^[0-9]{4}-[0-9]{2}-[0-9]{2})|(^[0-9]{4}-[0-9]{2})|(^[0-9]{4}))/(([0-9]{4}-[0-9]{2}-[0-9]{2}$)|([0-9]{4}-[0-9]{2}$)|([0-9]{4}$)))"
-        echo "$PUBLICATION_DATE" | grep -q -E "$RE_EDTF_LEVEL_0"
-        echo "publication_date is EDTF Level 0"
+	if ! (echo "$PUBLICATION_DATE" | grep -q -E "$RE_EDTF_LEVEL_0"); then
+            errlog "ERROR: publication_date '$PUBLICATION_DATE' is not valid EDTF Level 0."
+            exit 35
+	fi
+        log "publication_date is EDTF Level 0"
     else
-        echo "publication_date is empty or not given"
+        warnlog "publication_date is empty or not given"
     fi
 fi
 
@@ -208,7 +237,7 @@ if [ "$DEPLOY2ZENODO_DEPOSITION_ID" = "create NEW record" ]; then
                     log "Skip testing checksum due to DRYRUN or SKIPRUN."
                 else
                     test -n "$CHECKSUMRAW" -a "$CHECKSUMRAW" != "null" || (errlog "CHECKSUMRAW=\"$CHECKSUMRAW\""; exit 7)
-                    echo "$CHECKSUM  $filename" | md5sum -c -
+		    echo "$CHECKSUM  $filename" | md5sum -c - || (errlog "checksum verification failed: $CHECKSUM $filename"; exit 36)
                 fi
             done
             log "files uploaded"
@@ -241,7 +270,7 @@ if [ "$DEPLOY2ZENODO_DEPOSITION_ID" = "create NEW record" ]; then
                     CHECKSUMRAW=$(echo "$FILEUPLOAD" | jq -r .checksum)
                     test -n "$CHECKSUMRAW" -a "$CHECKSUMRAW" != "null" || (errlog "CHECKSUMRAW=\"$CHECKSUMRAW\""; exit 8)
                     CHECKSUM=$(echo "$CHECKSUMRAW" | cut -d ':' -f 2)
-                    echo "$CHECKSUM  $dummyfile" | md5sum -c -
+		    echo "$CHECKSUM  $dummyfile" | md5sum -c - || (errlog "checksum verification failed: $CHECKSUM $dummyfile"; exit 37)
                     PUBLISHRECORD=$(curlauth --max-time "$CURL_MAX_TIME_PUBLISH" --request POST "$LATESTDRAFT"/actions/publish)
                     echojq PUBLISHRECORD "$PUBLISHRECORD"
                 fi
@@ -409,7 +438,7 @@ else
                     log "Skip testing checksum due to DRYRUN or SKIPRUN."
                 else
                     test -n "$CHECKSUMRAW" -a "$CHECKSUMRAW" != "null" || (errlog "CHECKSUMRAW=\"$CHECKSUMRAW\""; exit 18)
-                    echo "$CHECKSUM  $filename" | md5sum -c -
+		    echo "$CHECKSUM  $filename" | md5sum -c - || (errlog "checksum verification failed: $CHECKSUM $filename"; exit 38)
                 fi
             done
             log "files uploaded"
@@ -442,7 +471,7 @@ else
                     CHECKSUMRAW=$(echo "$FILEUPLOAD" | jq -r .checksum)
                     test -n "$CHECKSUMRAW" -a "$CHECKSUMRAW" != "null" || (errlog "CHECKSUMRAW=\"$CHECKSUMRAW\""; exit 19)
                     CHECKSUM=$(echo "$CHECKSUMRAW" | cut -d ':' -f 2)
-                    echo "$CHECKSUM  $dummyfile" | md5sum -c -
+		    echo "$CHECKSUM  $dummyfile" | md5sum -c - || (errlog "checksum verification failed: $CHECKSUM $dummyfile"; exit 39)
                     PUBLISHRECORD=$(curlauth --max-time "$CURL_MAX_TIME_PUBLISH" --request POST "$LATESTDRAFT"/actions/publish)
                     echojq PUBLISHRECORD "$PUBLISHRECORD"
                 fi
@@ -474,6 +503,6 @@ if [ -n "$DEPLOY2ZENODO_GET_METADATA" ]; then
     fi
 fi
 
-echo "$(date -Iseconds) finished deploy2zenodo v$VERSION"
+log "$(date -Iseconds) finished deploy2zenodo v$VERSION"
 
 # stop deploy2zenodo
